blueprint:
  name: Go-eCharger High Level Mode
  description: Set the high level mode of the go-eCharger
  domain: template

  input:
    mode_input:
      name: "Mode input"
      description: |
        A `text_input` which is needed to store the current mode in a proper way.
        This is only used by this template sensor and is not intended to be included in the UI.
        Create an empty input text, e.g. like this:
        ```yaml
        input_text:
          wallbox_mode_internal:
            name: "Wallbox mode"
        ```

      selector:
        entity:
          domain: input_text
    power_levels:
      name: "Power levels"
      description: |
        List of power levels for setting a static level.
        If you add custom values in addition to the predefined ones, you need to map them to phase & current in the
        when using the `go-e-charger-automation.yaml` blueprint (using the `power_level_mapping` input).
        Defaults to "5.5 kW", "11 kW".
      selector:
        select:
          options:
            - "1.4 kW"
            - "5.5 kW"
            - "11 kW"
            - "22 kW"
          multiple: true
          custom_value: true
      default:
        - "5.5 kW"
        - "11 kW"


variables:
  input_power_levels: !input power_levels
  input_mode_input: !input mode_input


select:
  options: '{{ ["Auto", "PV", "Off"] + input_power_levels }}'
  state: "{{ states(input_mode_input) }}"
  icon: >
    {% if is_state(input_mode_input, "Off") %}
      mdi:power-plug-off
    {% elif is_state(input_mode_input, "Auto") %}
      mdi:solar-power
    {% elif is_state(input_mode_input, "PV") %}
      mdi:solar-power
    {% else %}
      mdi:lightning-bolt
    {% endif %}
  select_option:
    - service: input_text.set_value
      data:
        entity_id: !input mode_input
        value: "{{ option }}"