blueprint:
  name: Go-eCharger Status
  description: Show the current status of the go-e Charger in a compact way
  domain: template
  input:
    charger_allowed_to_charge:
      name: "Charger allowed to charge"
      description: "Whether the charger is allowed to charge or not"
      selector:
        entity:
          domain: binary_sensor
          integration: mqtt
    charger_power:
      name: "Charger power"
      description: "The current total power of the charger in W"
      selector:
        entity:
          domain: sensor
          integration: mqtt
          device_class: power
    charger_logic_mode:
      name: "Charger logic mode"
      description: "The current logic mode of the charger"
      selector:
        entity:
          domain: sensor
          integration: mqtt

variables:
  input_charger_allowed_to_charge: !input charger_allowed_to_charge
  input_charger_power: !input charger_power
  input_charger_logic_mode: !input charger_logic_mode


sensor:
  state: >
    {% if states(input_charger_power) in ["unknown", "unavailable"] %}
      {{ states(input_charger_power) }}
    {% else %}
      {{ ((states(input_charger_power) | float) / 1000) | round(1) }}
    {% endif %}
  unit_of_measurement: "kW"
  attributes:
    info: >
      {% if states(input_charger_power) in ["unknown", "unavailable"] %}
        {{ states(input_charger_power) }}
      {% elif is_state(input_charger_allowed_to_charge, "off") %}
        Off
      {% else %}
        {% if states(input_charger_power) | float == 0 %}
          Idle
        {% else %} 
          Charging ({{ ((states(input_charger_power) | float) / 1000)|round(1) }} kW)
        {% endif %}
      {% endif %}

  icon: >
    {% if states(input_charger_power) in ["unknown", "unavailable"] %}
        mdi:alert
    {% elif is_state(input_charger_allowed_to_charge, "off") %}
      mdi:power-plug-off
    {% else %}
      {% if states(input_charger_power) | float == 0 %}
          mdi:power-standby
      {% else %} 
        {% if states(input_charger_logic_mode) == "Eco" %}
          mdi:solar-power
        {% else %}
          mdi:lightning-bolt
        {% endif %} 
      {% endif %}
    {% endif %}